# Generated by Django 2.2.6 on 2019-11-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_gabinete', models.CharField(max_length=15)),
                ('nombre_gabinete', models.CharField(max_length=30)),
                ('tipo_gabinete', models.CharField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX')], default='ATX', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.CharField(choices=[('n', 'NVIDIA'), ('a', 'AMD')], default='n', max_length=1)),
                ('graphN', models.CharField(max_length=50)),
                ('gb', models.CharField(max_length=2)),
                ('frecMin', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Proce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proce', models.CharField(choices=[('i', 'Intel'), ('a', 'AMD')], default='i', max_length=1)),
                ('proceN', models.CharField(max_length=50)),
                ('core', models.CharField(max_length=3)),
                ('threads', models.CharField(max_length=3)),
                ('frecMini', models.CharField(max_length=4)),
                ('frecMax', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcr', models.CharField(max_length=10)),
                ('nomr', models.CharField(max_length=30)),
                ('gbs', models.CharField(max_length=2)),
                ('frecMinn', models.CharField(max_length=5)),
                ('volt', models.CharField(max_length=5)),
            ],
        ),
    ]
