# Generated by Django 2.2.6 on 2019-11-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191106_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='frecMin',
            field=models.CharField(max_length=4),
        ),
    ]
