# Generated by Django 2.2.6 on 2019-11-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191106_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gab',
            name='tipo_gabinete',
            field=models.CharField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX')], default='ATX', max_length=10),
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph',
            field=models.CharField(choices=[('NVIDIA', 'NVIDIA'), ('AMD', 'AMD')], default='NVIDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='proce',
            name='proce',
            field=models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=10),
        ),
    ]
