# Generated by Django 2.2.6 on 2019-11-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191107_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proce',
            name='proce',
            field=models.CharField(max_length=10),
        ),
    ]
