# Generated by Django 2.2.6 on 2019-11-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191107_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='graph',
            field=models.CharField(max_length=10),
        ),
    ]
