# Generated by Django 2.2.6 on 2019-11-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191107_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gab',
            name='marca_gabinete',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gab',
            name='nombre_gabinete',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='gab',
            name='tipo_gabinete',
            field=models.CharField(max_length=10),
        ),
    ]
