# Generated by Django 2.2.6 on 2019-11-12 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191107_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_Proce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='proce',
            name='proce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Marca_Proce'),
        ),
    ]
