# Generated by Django 2.2.6 on 2019-11-12 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191111_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proce',
            name='proce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Marca_Proce'),
        ),
    ]
