# Generated by Django 2.2.6 on 2019-11-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191112_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca_gab',
            old_name='nom',
            new_name='nomge',
        ),
        migrations.RenameField(
            model_name='marca_graph',
            old_name='nom',
            new_name='nomg',
        ),
    ]
