# Generated by Django 2.2.6 on 2019-11-12 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191112_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gab',
            name='marca_gabinete',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='gab',
            name='tipo_gabinete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Marca_Gab'),
        ),
    ]
